# Generated by Django 5.1.5 on 2026-09-01 09:52

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='APIKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('prefix', models.CharField(max_length=8, unique=True)),
                ('secret_hash', models.CharField(max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_used_at', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='api_keys', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ShortURL',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=32, unique=True)),
                ('destination', models.TextField()),
                ('title', models.CharField(blank=True, max_length=120)),
                ('is_custom_alias', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('password_hash', models.CharField(blank=True, max_length=128)),
                ('password_updated_at', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('click_count', models.BigIntegerField(default=0)),
                ('last_clicked_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='urls', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ClickEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('ip_hash', models.CharField(blank=True, max_length=32)),
                ('country', models.CharField(blank=True, max_length=2)),
                ('region', models.CharField(blank=True, max_length=64)),
                ('city', models.CharField(blank=True, max_length=64)),
                ('device', models.CharField(choices=[('desktop', 'Desktop'), ('mobile', 'Mobile'), ('tablet', 'Tablet'), ('bot', 'Bot'), ('unknown', 'Unknown')], default='unknown', max_length=16)),
                ('browser', models.CharField(blank=True, max_length=40)),
                ('os', models.CharField(blank=True, max_length=40)),
                ('referrer_host', models.CharField(blank=True, max_length=255)),
                ('user_agent', models.CharField(blank=True, max_length=400)),
                ('short_url', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clicks', to='shortener.shorturl')),
            ],
        ),
        migrations.AddIndex(
            model_name='shorturl',
            index=models.Index(fields=['owner', '-created_at'], name='shorturl_owner_created_idx'),
        ),
        migrations.AddIndex(
            model_name='shorturl',
            index=models.Index(condition=models.Q(('expires_at__isnull', False)), fields=['expires_at'], name='shorturl_expires_idx'),
        ),
        migrations.AddIndex(
            model_name='clickevent',
            index=models.Index(fields=['short_url', '-created_at'], name='click_url_created_idx'),
        ),
        migrations.AddIndex(
            model_name='clickevent',
            index=models.Index(fields=['created_at'], name='click_created_idx'),
        ),
    ]
