# Generated by Django 5.1.5 on 2026-09-02 05:26

from django.conf import settings
from django.db import migrations, models


def release_deleted_codes(apps, schema_editor):
    """Links deleted before this change were still holding their aliases."""
    ShortURL = apps.get_model("shortener", "ShortURL")
    ShortURL.objects.filter(deleted_at__isnull=False, code_released_at__isnull=True).update(
        code_released_at=models.F("deleted_at")
    )


def reclaim_deleted_codes(apps, schema_editor):
    ShortURL = apps.get_model("shortener", "ShortURL")
    ShortURL.objects.filter(code_released_at__isnull=False).update(code_released_at=None)


class Migration(migrations.Migration):

    dependencies = [
        ('shortener', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='shorturl',
            name='code_released_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='shorturl',
            name='code',
            field=models.CharField(max_length=32),
        ),
        migrations.AddConstraint(
            model_name='shorturl',
            constraint=models.UniqueConstraint(condition=models.Q(('code_released_at__isnull', True)), fields=('code',), name='shorturl_unique_live_code'),
        ),
        migrations.RunPython(release_deleted_codes, reclaim_deleted_codes),
    ]
